"""GEAKG: Generative Executable Algorithm Knowledge Graph.

NS-SE (Neuro-Symbolic Search Evolution) uses a 3-layer GEAKG architecture:

    L0: MetaGraph Topology (offline, LLM) - src/geakg/layers/l0/
    L1: Operator Generation (offline, LLM) - src/geakg/layers/l1/
    L2: ACO Training (offline, ACO) - src/geakg/layers/l2/
    Offline: Training pipeline - src/geakg/offline/
    Online: Symbolic Executor - src/geakg/online/
    Transfer: Domain Adapters - src/geakg/transfer/

Core concepts:
- Generative: Structure and operators are generated by LLM
- Executable: Nodes contain executable code (not just descriptions)
- Algorithm: Represents algorithmic optimization strategies
- Knowledge Graph: Graph structure with roles, transitions, and learned weights
"""

from src.geakg.graph import AlgorithmicKnowledgeGraph, Trajectory
from src.geakg.nodes import (
    AKGEdge,
    AKGNode,
    DataStructureNode,
    EdgeType,
    NodeType,
    OperatorCategory,
    OperatorNode,
    PropertyNode,
)
from src.geakg.ontology import create_default_akg, get_operator_summary

# Re-export main classes from layers
from src.geakg.layers.l0 import AbstractRole, RoleCategory, MetaGraph, MetaEdge
from src.geakg.layers.l1 import Operator, OperatorPool
from src.geakg.layers.l2 import GEAKGSnapshot, PheromoneMatrix

# Core abstractions for generalization
from src.geakg.core import CaseStudy, RoleSchema

__all__ = [
    # Core graph
    "AlgorithmicKnowledgeGraph",
    "Trajectory",
    "AKGNode",
    "AKGEdge",
    "OperatorNode",
    "DataStructureNode",
    "PropertyNode",
    "NodeType",
    "EdgeType",
    "OperatorCategory",
    "create_default_akg",
    "get_operator_summary",
    # Layers
    "AbstractRole",
    "RoleCategory",
    "MetaGraph",
    "MetaEdge",
    "Operator",
    "OperatorPool",
    "GEAKGSnapshot",
    "PheromoneMatrix",
    # Core abstractions
    "CaseStudy",
    "RoleSchema",
]
