"""Program templates for different domains.

Each template generates a standalone Python file that can execute the best
program found by NS-GE on new instances of the same problem type.

Templates are domain-specific because:
- Solution representation differs (permutation, scheduling, packing)
- Fitness evaluation differs
- Instance loading differs
"""

# =============================================================================
# TSP Template
# =============================================================================

TSP_PROGRAM_TEMPLATE = '''#!/usr/bin/env python3
"""Best {domain} program - Generated by NS-GE on {timestamp}

Performance:
    Gap to optimal: {gap:.2f}%
    Best fitness: {fitness:.2f}
    Total evaluations: {evals}
    Elapsed time: {elapsed:.1f}s

This file is self-contained and can be executed directly:
    python best_program.py path/to/instance.tsp
"""
from __future__ import annotations

import math
import random
import sys
from typing import Any, Callable

# =============================================================================
# Metadata
# =============================================================================
DOMAIN = "{domain}"
BEST_OPERATOR_PATH = {operator_path}
BEST_ROLE_PATH = {role_path}

# =============================================================================
# DomainContext for agnostic operators (Lampson: "Keep secrets")
# =============================================================================
class TSPContext:
    """TSP domain context - hides distance_matrix from operators."""

    def __init__(self, distance_matrix: list[list[float]]):
        self._dm = distance_matrix
        self._n = len(distance_matrix)

    def cost(self, tour: list[int], i: int) -> float:
        """Cost contribution of city at position i."""
        n = len(tour)
        prev_i, next_i = (i - 1) % n, (i + 1) % n
        return self._dm[tour[prev_i]][tour[i]] + self._dm[tour[i]][tour[next_i]]

    def delta(self, tour: list[int], move: str, i: int, j: int) -> float:
        """Delta cost if move(i,j) were applied."""
        if move == "swap":
            return self._swap_delta(tour, i, j)
        elif move == "2opt":
            return self._2opt_delta(tour, i, j)
        return 0.0

    def _swap_delta(self, tour: list[int], i: int, j: int) -> float:
        old_cost = self.cost(tour, i) + self.cost(tour, j)
        tour[i], tour[j] = tour[j], tour[i]
        new_cost = self.cost(tour, i) + self.cost(tour, j)
        tour[i], tour[j] = tour[j], tour[i]
        return new_cost - old_cost

    def _2opt_delta(self, tour: list[int], i: int, j: int) -> float:
        if i > j:
            i, j = j, i
        n = len(tour)
        a, b = tour[i], tour[(i + 1) % n]
        c, d = tour[j], tour[(j + 1) % n]
        return (self._dm[a][c] + self._dm[b][d]) - (self._dm[a][b] + self._dm[c][d])

    def neighbors(self, tour: list[int], i: int, k: int) -> list[int]:
        """K nearest positions by distance."""
        city = tour[i]
        dists = [(j, self._dm[city][tour[j]]) for j in range(len(tour)) if j != i]
        dists.sort(key=lambda x: x[1])
        return [idx for idx, _ in dists[:k]]

    def evaluate(self, tour: list[int]) -> float:
        """Total tour cost."""
        return sum(self._dm[tour[i]][tour[(i + 1) % len(tour)]] for i in range(len(tour)))

    def valid(self, tour: list[int]) -> bool:
        """Check if tour is valid permutation."""
        return len(tour) == self._n and set(tour) == set(range(self._n))


# =============================================================================
# Generic operators (raw functions)
# =============================================================================
{generic_operators_code}

# =============================================================================
# Synthesized Synthesized operators (use agnostic signature: solution, ctx)
# =============================================================================
{synth_operators_code}

# =============================================================================
# Helper functions for generic operators
# =============================================================================

def _invert(perm: list[int], i: int | None = None, j: int | None = None) -> list[int]:
    """Invert (reverse) segment from position i to j."""
    n = len(perm)
    if n < 2:
        return perm[:]
    if i is None or j is None:
        i, j = sorted(random.sample(range(n), 2))
    if i > j:
        i, j = j, i
    result = perm[:]
    result[i : j + 1] = reversed(result[i : j + 1])
    return result


def _insert(perm: list[int], i: int | None = None, j: int | None = None) -> list[int]:
    """Remove element at position i and insert at position j."""
    n = len(perm)
    if n < 2:
        return perm[:]
    if i is None:
        i = random.randint(0, n - 1)
    if j is None:
        j = random.randint(0, n - 1)
        while j == i:
            j = random.randint(0, n - 1)
    result = perm[:]
    elem = result.pop(i)
    result.insert(j, elem)
    return result


def insert(perm: list[int], i: int | None = None, j: int | None = None) -> list[int]:
    """Public insert wrapper."""
    return _insert(perm, i, j)


def invert(perm: list[int], i: int | None = None, j: int | None = None) -> list[int]:
    """Public invert wrapper."""
    return _invert(perm, i, j)


# =============================================================================
# Agnostic wrappers for complex generic operators
# These wrap operators that need ctx for evaluation
# =============================================================================

def _wrap_variable_depth_search(solution: list[int], ctx) -> list[int]:
    """Variable depth search using ctx.evaluate."""
    best = solution[:]
    best_cost = ctx.evaluate(best)

    for depth in range(1, 4):
        current = best[:]
        for _ in range(depth * 5):
            candidate = swap(current)
            candidate_cost = ctx.evaluate(candidate)
            if candidate_cost < best_cost:
                best = candidate
                best_cost = candidate_cost
                current = candidate
    return best


def _wrap_vnd_generic(solution: list[int], ctx) -> list[int]:
    """Variable neighborhood descent using ctx.evaluate."""
    best = solution[:]
    best_cost = ctx.evaluate(best)

    neighborhoods = [swap, insert, invert]
    improved = True
    max_iters = 20
    iters = 0

    while improved and iters < max_iters:
        improved = False
        iters += 1
        for neighborhood in neighborhoods:
            candidate = neighborhood(best)
            candidate_cost = ctx.evaluate(candidate)
            if candidate_cost < best_cost:
                best = candidate
                best_cost = candidate_cost
                improved = True
                break
    return best


# =============================================================================
# Operator registry - all operators have signature (solution, ctx)
# =============================================================================
OPERATORS = {{
{operator_registry}
}}

# =============================================================================
# TSP-specific code
# =============================================================================

def tour_cost(tour: list[int], distance_matrix: list[list[float]]) -> float:
    """Calculate total tour cost."""
    cost = 0.0
    n = len(tour)
    for i in range(n):
        cost += distance_matrix[tour[i]][tour[(i + 1) % n]]
    return cost


def load_tsplib(filepath: str) -> tuple[list[list[float]], float | None]:
    """Load TSPLIB format file.

    Returns:
        Tuple of (distance_matrix, optimal_cost or None)
    """
    with open(filepath) as f:
        content = f.read()

    lines = content.strip().split("\\n")
    dimension = 0
    edge_weight_type = "EUC_2D"
    optimal_cost = None
    i = 0

    while i < len(lines):
        line = lines[i].strip()
        if line.startswith("DIMENSION"):
            dimension = int(line.split(":")[1].strip())
        elif line.startswith("EDGE_WEIGHT_TYPE"):
            edge_weight_type = line.split(":")[1].strip()
        elif line.startswith("NODE_COORD_SECTION"):
            i += 1
            break
        elif "optimal" in line.lower():
            import re
            match = re.search(r"(\\d+(?:\\.\\d+)?)", line)
            if match:
                optimal_cost = float(match.group(1))
        i += 1

    coordinates = []
    while i < len(lines):
        line = lines[i].strip()
        if line == "EOF" or line.startswith("DISPLAY"):
            break
        parts = line.split()
        if len(parts) >= 3:
            x, y = float(parts[1]), float(parts[2])
            coordinates.append((x, y))
        i += 1

    n = len(coordinates)
    matrix = [[0.0] * n for _ in range(n)]

    for i in range(n):
        for j in range(n):
            if i != j:
                x1, y1 = coordinates[i]
                x2, y2 = coordinates[j]
                if edge_weight_type == "EUC_2D":
                    matrix[i][j] = math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)
                elif edge_weight_type == "CEIL_2D":
                    matrix[i][j] = math.ceil(math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2))
                else:
                    matrix[i][j] = math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)

    return matrix, optimal_cost


def run_program(
    distance_matrix: list[list[float]],
    n_runs: int = 10,
    timeout: float | None = None,
    optimal: float | None = None,
    verbose: bool = False,
) -> tuple[list[int], float, int]:
    """Execute the best program on a distance matrix.

    All operators use the domain-agnostic signature: operator(solution, ctx)
    Following Lampson's "Keep secrets" - distance_matrix is hidden in ctx.

    Args:
        distance_matrix: Square distance matrix.
        n_runs: Number of independent runs.
        timeout: Maximum time in seconds (None = no limit).
        optimal: Known optimal for gap calculation.
        verbose: Print progress.

    Returns:
        Tuple of (best_tour, best_cost, runs_completed)
    """
    import time
    best_tour, best_cost = None, float("inf")
    n = len(distance_matrix)
    start_time = time.time()
    runs_completed = 0

    # Create context once - operators use ctx, not distance_matrix directly
    ctx = TSPContext(distance_matrix)

    for run in range(n_runs):
        # Check timeout
        if timeout and (time.time() - start_time) >= timeout:
            if verbose:
                print(f"\\n[Timeout reached after {{runs_completed}} runs]")
            break

        # Start with random permutation
        solution = list(range(n))
        random.shuffle(solution)

        # Apply operator sequence using agnostic signature
        for op_name in BEST_OPERATOR_PATH:
            if op_name not in OPERATORS:
                if verbose:
                    print(f"Warning: operator {{op_name}} not found, skipping")
                continue

            op = OPERATORS[op_name]

            # All operators use agnostic signature: (solution, ctx)
            try:
                result = op(solution, ctx)
                if isinstance(result, list) and len(result) == n and ctx.valid(result):
                    solution = result
            except Exception as e:
                if verbose:
                    print(f"Warning: operator {{op_name}} failed: {{e}}")

        cost = ctx.evaluate(solution)
        improved = cost < best_cost
        if improved:
            best_tour, best_cost = solution.copy(), cost

        runs_completed += 1

        if verbose and improved:
            gap_str = ""
            if optimal and optimal > 0:
                gap = 100 * (cost - optimal) / optimal
                gap_str = f" (gap={{gap:.2f}}%)"
            print(f"Run {{run + 1}}/{{n_runs}}: cost={{cost:.2f}}{{gap_str}} *")

    return best_tour, best_cost, runs_completed


def main(args: list[str]) -> None:
    """Main entry point."""
    import argparse
    import json
    parser = argparse.ArgumentParser(description="Run NS-SE best program on TSP instance")
    parser.add_argument("instance", help="Path to TSPLIB instance file")
    parser.add_argument("-n", "--n-runs", type=int, default=None, help="Number of runs (default: 10, or unlimited if timeout set)")
    parser.add_argument("-t", "--timeout", type=float, default=None, help="Timeout in seconds (default: no limit)")
    parser.add_argument("--optimal", type=float, default=None, help="Known optimal cost (overrides file)")
    parser.add_argument("-q", "--quiet", action="store_true", help="Suppress per-run output")
    parser.add_argument("-o", "--output", type=str, default=None, help="Save results to JSON file")
    parsed = parser.parse_args(args)

    # If timeout is set and n_runs not specified, use unlimited runs
    if parsed.timeout and parsed.n_runs is None:
        n_runs = 999999999  # Effectively unlimited
    else:
        n_runs = parsed.n_runs or 10  # Default to 10 if neither specified

    print(f"Loading instance: {{parsed.instance}}")
    distance_matrix, file_optimal = load_tsplib(parsed.instance)
    optimal = parsed.optimal or file_optimal
    print(f"Instance size: {{len(distance_matrix)}} cities")

    if optimal:
        print(f"Known optimal: {{optimal:.2f}}")

    print(f"\\nRunning best program...")
    if parsed.timeout:
        print(f"  Timeout: {{parsed.timeout}}s")
        if parsed.n_runs is None:
            print(f"  Runs: unlimited (until timeout)")
        else:
            print(f"  Runs: {{n_runs}} (max)")
    else:
        print(f"  Runs: {{n_runs}}")
    print(f"  Operators: {{len(BEST_OPERATOR_PATH)}} in path")
    if BEST_OPERATOR_PATH:
        print(f"  Path: {{BEST_OPERATOR_PATH[:3]}}..." if len(BEST_OPERATOR_PATH) > 3 else f"  Path: {{BEST_OPERATOR_PATH}}")
    print()

    best_tour, best_cost, runs_completed = run_program(
        distance_matrix,
        n_runs=n_runs,
        timeout=parsed.timeout,
        optimal=optimal,
        verbose=not parsed.quiet,
    )

    print(f"\\n{{'=' * 50}}")
    print(f"Runs completed: {{runs_completed}}")
    print(f"Best tour cost: {{best_cost:.2f}}")
    if optimal and optimal > 0:
        gap = 100 * (best_cost - optimal) / optimal
        print(f"Gap to optimal: {{gap:.2f}}%")
    if best_tour:
        print(f"Tour: {{best_tour[:10]}}..." if len(best_tour) > 10 else f"Tour: {{best_tour}}")


if __name__ == "__main__":
    main(sys.argv[1:])
'''

# =============================================================================
# JSSP Template (placeholder - to be implemented)
# =============================================================================

JSSP_PROGRAM_TEMPLATE = '''#!/usr/bin/env python3
"""Best {domain} program - Generated by NS-GE on {timestamp}

Performance:
    Gap to optimal: {gap:.2f}%
    Best fitness (makespan): {fitness:.2f}
    Total evaluations: {evals}
    Elapsed time: {elapsed:.1f}s

This file is self-contained and can be executed directly:
    python best_program.py path/to/instance.txt
"""
from __future__ import annotations

import random
import sys
from typing import Any

# =============================================================================
# Metadata
# =============================================================================
DOMAIN = "{domain}"
BEST_OPERATOR_PATH = {operator_path}
BEST_ROLE_PATH = {role_path}

# =============================================================================
# Generic operators
# =============================================================================
{generic_operators_code}

# =============================================================================
# Synthesized Synthesized operators
# =============================================================================
{synth_operators_code}

# =============================================================================
# Operator registry
# =============================================================================
OPERATORS = {{
{operator_registry}
}}

# =============================================================================
# JSSP-specific code (to be implemented)
# =============================================================================

def main(args: list[str]) -> None:
    """Main entry point."""
    print("JSSP support not yet implemented in standalone program")
    print(f"Operator path: {{BEST_OPERATOR_PATH}}")


if __name__ == "__main__":
    main(sys.argv[1:])
'''

# =============================================================================
# VRP Template (placeholder)
# =============================================================================

VRP_PROGRAM_TEMPLATE = '''#!/usr/bin/env python3
"""Best {domain} program - Generated by NS-GE on {timestamp}

Performance:
    Gap to optimal: {gap:.2f}%
    Best fitness: {fitness:.2f}
    Total evaluations: {evals}
    Elapsed time: {elapsed:.1f}s
"""
from __future__ import annotations

import sys
from typing import Any

DOMAIN = "{domain}"
BEST_OPERATOR_PATH = {operator_path}
BEST_ROLE_PATH = {role_path}

{generic_operators_code}

{synth_operators_code}

OPERATORS = {{
{operator_registry}
}}

def main(args: list[str]) -> None:
    print("VRP support not yet implemented in standalone program")
    print(f"Operator path: {{BEST_OPERATOR_PATH}}")

if __name__ == "__main__":
    main(sys.argv[1:])
'''

# =============================================================================
# BPP Template (placeholder)
# =============================================================================

BPP_PROGRAM_TEMPLATE = '''#!/usr/bin/env python3
"""Best {domain} program - Generated by NS-GE on {timestamp}

Performance:
    Gap to optimal: {gap:.2f}%
    Best fitness: {fitness:.2f}
    Total evaluations: {evals}
    Elapsed time: {elapsed:.1f}s
"""
from __future__ import annotations

import sys
from typing import Any

DOMAIN = "{domain}"
BEST_OPERATOR_PATH = {operator_path}
BEST_ROLE_PATH = {role_path}

{generic_operators_code}

{synth_operators_code}

OPERATORS = {{
{operator_registry}
}}

def main(args: list[str]) -> None:
    print("BPP support not yet implemented in standalone program")
    print(f"Operator path: {{BEST_OPERATOR_PATH}}")

if __name__ == "__main__":
    main(sys.argv[1:])
'''

# =============================================================================
# Template Registry
# =============================================================================

PROGRAM_TEMPLATES = {
    "tsp": TSP_PROGRAM_TEMPLATE,
    "jssp": JSSP_PROGRAM_TEMPLATE,
    "vrp": VRP_PROGRAM_TEMPLATE,
    "bpp": BPP_PROGRAM_TEMPLATE,
}


def get_program_template(domain: str) -> str:
    """Get program template for a domain.

    Args:
        domain: Domain name (tsp, jssp, vrp, bpp).

    Returns:
        Template string.

    Raises:
        ValueError: If domain not supported.
    """
    domain = domain.lower()
    if domain not in PROGRAM_TEMPLATES:
        raise ValueError(
            f"Unknown domain '{domain}'. Supported: {list(PROGRAM_TEMPLATES.keys())}"
        )
    return PROGRAM_TEMPLATES[domain]
