"""Program Generator: Export best operator sequences as standalone Python programs.

Generates executable Python files from operator paths, with:
- Unique operators only (no duplicates even if path repeats them)
- TSP context and instance loading
- Self-contained execution
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

from loguru import logger

if TYPE_CHECKING:
    from src.geakg.layers.l1.pool import OperatorPool


def generate_best_program(
    pool: "OperatorPool",
    role_path: list[str],
    operator_path: list[str],
    output_path: Path,
    gap: float = 0.0,
    round_num: int | None = None,
    domain: str = "tsp",
) -> Path:
    """Generate best_program.py from operator path and pool.

    Args:
        pool: Operator pool with all operators
        role_path: Best role path
        operator_path: Best operator path
        output_path: Where to save the program
        gap: Best gap achieved
        round_num: Round number (for title)
        domain: Domain name

    Returns:
        Path to generated program
    """
    from src.geakg.layers.l1.base_operators import BASE_OPERATORS

    # Collect UNIQUE operators (preserve order of first appearance)
    unique_operators = []
    seen = set()
    for op_name in operator_path:
        if op_name not in seen:
            unique_operators.append(op_name)
            seen.add(op_name)

    # Collect operator code
    operator_code, op_to_fn = _collect_operator_code(pool, unique_operators, BASE_OPERATORS)
    registry_code = _build_registry(unique_operators, op_to_fn)

    # Generate program
    round_str = f" (Round {round_num})" if round_num else ""
    program = _get_template().format(
        round_str=round_str,
        timestamp=datetime.now().isoformat(),
        gap=gap,
        n_operators=len(operator_path),
        n_unique=len(unique_operators),
        filename=output_path.name,
        domain=domain.upper(),
        operator_path=repr(operator_path),
        role_path=repr(role_path),
        operators_code=operator_code,
        registry_code=registry_code,
    )

    output_path.write_text(program)
    logger.info(f"[PROGRAM] Generated {output_path.name} ({len(unique_operators)} unique operators)")
    return output_path


def _extract_function_name(code: str) -> str | None:
    """Extract function name from code."""
    import re
    match = re.search(r"def\s+(\w+)\s*\(", code)
    return match.group(1) if match else None


def _collect_operator_code(
    pool: "OperatorPool",
    unique_operators: list[str],
    base_operators: dict[str, str],
) -> tuple[str, dict[str, str]]:
    """Collect code for unique operators.

    Returns:
        (code_string, op_name_to_fn_name_mapping)
    """
    lines = []
    op_to_fn = {}  # Maps operator name to function name

    for op_name in unique_operators:
        code = None

        # Try pool first
        for role in pool.roles:
            for op in pool.get_operators_for_role(role):
                if op.name == op_name:
                    code = op.code
                    break
            if code:
                break

        # Fallback to base operators
        if not code:
            for role, base_code in base_operators.items():
                if op_name == f"{role}_base":
                    code = base_code
                    break

        if code:
            fn_name = _extract_function_name(code) or op_name
            op_to_fn[op_name] = fn_name
            lines.append(f"# Operator: {op_name}")
            lines.append(code.strip())
            lines.append("")

    return "\n".join(lines) if lines else "pass", op_to_fn


def _build_registry(unique_operators: list[str], op_to_fn: dict[str, str]) -> str:
    """Build operator registry code."""
    lines = []
    for op in unique_operators:
        fn_name = op_to_fn.get(op, op)
        lines.append(f'    "{op}": {fn_name},')
    return "\n".join(lines) if lines else "    pass"


def _get_template() -> str:
    """Get program template."""
    return '''#!/usr/bin/env python3
"""Best TSP program{round_str} - Generated by NS-SE on {timestamp}

Performance:
    Best gap: {gap:.2f}%
    Operators in path: {n_operators}
    Unique operators: {n_unique}

Usage:
    python {filename} instance.tsp              # 10 runs (default)
    python {filename} instance.tsp -n 100       # 100 runs
    python {filename} instance.tsp -t 60        # 60 seconds timeout
    python {filename} instance.tsp --optimal 7542  # specify known optimal
"""
from __future__ import annotations

import math
import random
import sys

DOMAIN = "{domain}"
BEST_OPERATOR_PATH = {operator_path}
BEST_ROLE_PATH = {role_path}


class TSPContext:
    def __init__(self, dm: list[list[float]]):
        self._dm = dm
        self._n = len(dm)

    def evaluate(self, tour: list[int]) -> float:
        if len(tour) < 2:
            return 0.0
        return sum(self._dm[tour[i]][tour[(i + 1) % len(tour)]] for i in range(len(tour)))

    def valid(self, tour: list[int]) -> bool:
        return len(tour) == self._n and set(tour) == set(range(self._n))


# === Operators ===
{operators_code}

OPERATORS = {{
{registry_code}
}}


def load_tsplib(filepath: str) -> tuple[list[list[float]], float | None]:
    with open(filepath) as f:
        lines = f.read().strip().split("\\n")

    edge_type, optimal, i = "EUC_2D", None, 0
    while i < len(lines):
        line = lines[i].strip()
        if line.startswith("EDGE_WEIGHT_TYPE"):
            edge_type = line.split(":")[1].strip()
        elif line.startswith("NODE_COORD_SECTION"):
            i += 1
            break
        elif "optimal" in line.lower():
            import re
            # Match "optimal=5247" or "optimal: 5247" or "optimal 5247"
            m = re.search(r"optimal[=:\\s]+?(\\d+(?:\\.\\d+)?)", line.lower())
            if m: optimal = float(m.group(1))
        i += 1

    coords = []
    while i < len(lines) and not lines[i].strip().startswith(("EOF", "DISPLAY")):
        parts = lines[i].split()
        if len(parts) >= 3:
            coords.append((float(parts[1]), float(parts[2])))
        i += 1

    n = len(coords)
    dm = [[0.0] * n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            if i != j:
                dx, dy = coords[j][0] - coords[i][0], coords[j][1] - coords[i][1]
                d = math.sqrt(dx*dx + dy*dy)
                dm[i][j] = math.ceil(d) if edge_type == "CEIL_2D" else d
    return dm, optimal


def run(dm, n_runs=10, timeout=None):
    import time
    best_tour, best_cost = None, float("inf")
    n, start, ctx = len(dm), time.time(), TSPContext(dm)

    for _ in range(n_runs):
        if timeout and time.time() - start >= timeout:
            break
        sol = list(range(n))
        random.shuffle(sol)
        for op_name in BEST_OPERATOR_PATH:
            if op_name in OPERATORS:
                try:
                    r = OPERATORS[op_name](sol, ctx)
                    if isinstance(r, list) and ctx.valid(r):
                        sol = r
                except Exception:
                    pass
        cost = ctx.evaluate(sol)
        if cost < best_cost:
            best_tour, best_cost = sol[:], cost
    return best_tour, best_cost


if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser(description="Run best TSP program")
    p.add_argument("instance", help="Path to TSP instance file")
    p.add_argument("-n", "--runs", type=int, default=10, help="Number of runs (default: 10)")
    p.add_argument("-t", "--timeout", type=float, help="Time limit in seconds (overrides -n)")
    p.add_argument("--optimal", type=float, help="Known optimal value for gap calculation")
    args = p.parse_args()

    dm, opt = load_tsplib(args.instance)
    opt = args.optimal or opt
    n_runs = 999999999 if args.timeout else args.runs

    _, cost = run(dm, n_runs, args.timeout)
    print(f"Best: {{cost:.2f}}")
    if opt: print(f"Gap: {{100*(cost-opt)/opt:.2f}}%")
'''
